### ISSUE TITLE
Add Project Audit Events.

### ISSUE THREAD

**Issue by AjayKMehta** [chris-peterson/pwsh-gitlab#49] opened 2022-09-09 20:09 UTC
First off, thanks for creating this module.

Would it be possible to add functions to get all project audit events or a particular one using the [Project Audit Events API](https://docs.gitlab.com/ee/api/audit_events.html#project-audit-events)?

**Comment by chris-peterson** [comment] 2022-09-13 19:07
Thanks for the issue!  This is a duplicate of #16 -- I'll try to knock that out

**Comment by chris-peterson** [comment] 2022-09-13 22:25
`1.71.0` now has support for `Get-GitlabAuditEvent` -- you can provide a group ID, or a project ID, or you can filter global events by type

**Closed by chris-peterson** 2022-09-13 22:25 UTC
