### ISSUE TITLE
Add help for exported functions

### ISSUE THREAD

**Issue by Stephanevg** [chris-peterson/pwsh-gitlab#98] opened 2024-08-19 09:40 UTC
When trying to figure out how this module worked, I was searching for examples using `Get-Help'. I noticed when skimming through the code, that quite a few functions don't have comment based help in place.

The one I was looking at, was `Invoke-GitLabApi` .
Since so many cmdlets are dependant on this cmdlet, It would make sense to add bullet proof help to this one could be a good starting point :)

Cheers

**Comment by chris-peterson** [comment] 2024-08-24 21:41
Duplicate of #25

**Closed by chris-peterson** 2024-08-24 21:41 UTC
